server:
  servlet:
    context-path: null
  port: 8080
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/pruebadb'
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
jpa:
  properties:
    hibernate:
      use-new-id-generator-mappings: true
      dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
hibernate:
  naming: null
  implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
